In [1]:
# Load packages 
import pandas as pd

# import the cnci output
cnci=pd.read_csv('all/CNCI.index' ,sep='\t')

# filter in the column index for noncoding 
cnci=cnci[cnci['index']=='noncoding']

In [2]:
cnci

       Transcript ID      index     score start   end  length
1           STRG.2.1  noncoding -0.000410     0     0    1967
2           STRG.3.1  noncoding -0.008192   744   834    1751
10          STRG.8.1  noncoding -0.016794   123   369    1430
11          STRG.9.1  noncoding -0.000410     0     0     441
12         STRG.10.1  noncoding -0.000410     0     0     295
...              ...        ...       ...   ...   ...     ...
166269  STRG.89494.1  noncoding -0.000410     0     0     256
166271  STRG.89496.1  noncoding -0.000410  2577  2712    3547
166272  STRG.89497.1  noncoding -0.041779  3033  3180    3734
166273  STRG.89498.1  noncoding -0.057344    60   186     610
166274  STRG.89499.1  noncoding -0.040550     0   432    1325

[57896 rows x 6 columns]

In [3]:
# convert everything in lower case for the ID column 
cnci['Transcript ID'] = cnci['Transcript ID'].str.lower()

In [4]:
cnci

       Transcript ID      index     score start   end  length
1           strg.2.1  noncoding -0.000410     0     0    1967
2           strg.3.1  noncoding -0.008192   744   834    1751
10          strg.8.1  noncoding -0.016794   123   369    1430
11          strg.9.1  noncoding -0.000410     0     0     441
12         strg.10.1  noncoding -0.000410     0     0     295
...              ...        ...       ...   ...   ...     ...
166269  strg.89494.1  noncoding -0.000410     0     0     256
166271  strg.89496.1  noncoding -0.000410  2577  2712    3547
166272  strg.89497.1  noncoding -0.041779  3033  3180    3734
166273  strg.89498.1  noncoding -0.057344    60   186     610
166274  strg.89499.1  noncoding -0.040550     0   432    1325

[57896 rows x 6 columns]

In [5]:
# export cnci df 
cnci.to_csv('cnci_lncRNA.csv', sep='\t', index=False)